# Generated by Django 5.0.2 on 2024-02-18 05:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="type",
            field=models.CharField(
                choices=[
                    ("IT", "IT"),
                    ("Non-IT", "Non-IT"),
                    ("Agriculture", "Agriculture"),
                    ("Pharma", "Pharma"),
                ],
                max_length=100,
            ),
        ),
    ]
