# Generated by Django 5.0.2 on 2024-02-18 07:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_company_type"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Employee",
        ),
    ]
